# Generated by Django 4.1.7 on 2023-03-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=255)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('equipment_description', models.TextField()),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('software_rev', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('firmware_rev', models.CharField(blank=True, max_length=255, null=True)),
                ('utility_software', models.CharField(blank=True, max_length=255, null=True)),
                ('useful_life', models.IntegerField(blank=True, null=True)),
                ('obsolescence_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Retried', 'Retried'), ('Rejected', 'Rejected')], max_length=10, null=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('area_approval', models.CharField(blank=True, choices=[('Company', 'Company'), ('Location', 'Location'), ('System', 'System')], max_length=10, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('documents_name', models.CharField(blank=True, max_length=500, null=True)),
                ('documents_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentForm',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equipments.equipment')),
                ('application_restriction', models.TextField(blank=True, null=True)),
                ('hazardous_area_classification_met', models.BooleanField(blank=True, null=True)),
                ('other_approvals', models.TextField(blank=True, null=True)),
                ('manufactural_quality_good', models.BooleanField(blank=True, null=True)),
                ('installation_match_manufacturer_recommendations', models.BooleanField(blank=True, null=True)),
                ('installation_match_manufacturer_recommendations_if_no', models.TextField(blank=True, null=True)),
                ('maintainance_plan_agree_with_manufacturer_recommendations', models.BooleanField(blank=True, null=True)),
                ('maintainance_plan_agree_with_manufacturer_recommendations_if_no', models.BooleanField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('approval_based_on', models.TextField(blank=True, null=True)),
                ('prior_use_application', models.CharField(blank=True, max_length=255, null=True)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('obsolescence_status', models.CharField(blank=True, max_length=255, null=True)),
                ('obsolescence_date', models.DateField(blank=True, null=True)),
                ('useful_life', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_date', models.DateField(blank=True, null=True)),
                ('close_record', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
