# Generated by Django 3.2.18 on 2023-03-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentform',
            name='maintainance_plan_agree_with_manufacturer_recommendations_if_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
